name       : libgnomekbd
version    : 3.28.1
release    : 16
source     :
    - https://download.gnome.org/sources/libgnomekbd/3.28/libgnomekbd-3.28.1.tar.xz : 22dc59566d73c0065350f5a97340e62ecc7b08c4df19183804bb8be24c8fe870
homepage   : http://www.gnome.org
license    : LGPL-2.0-only
component  : desktop.gnome.core
summary    : XKB Hooks used by the GNOME Desktop
description: |
    The libgnomekbd package contains xkb hooks used by the GNOME Desktop.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libxklavier)
    - pkgconfig(ice)
    - intltool
rundeps    :
    - xmodmap
setup      : |
    %autogen --disable-schemas-compile --disable-static
build      : |
    %make
install    : |
    %make_install
