name       : libgnomekbd
version    : 3.26.1
release    : 14
source     :
    - https://download.gnome.org/sources/libgnomekbd/3.26/libgnomekbd-3.26.1.tar.xz : f7ca02631576e9b88aee1b1bae37ac1488b80ee7975f20a97f29e761a7172679
homepage   : http://www.gnome.org
license    : LGPL-2.0-only
component  : desktop.gnome.core
summary    : XKB Hooks used by the GNOME Desktop
description: |
    The libgnomekbd package contains xkb hooks used by the GNOME Desktop.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libxklavier)
    - pkgconfig(ice)
    - intltool
rundeps    :
    - xmodmap
setup      : |
    %configure --disable-schemas-compile --disable-static
build      : |
    %make
install    : |
    %make_install
