name       : libgnomekbd
version    : 3.22.0.1
release    : 8
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/libgnomekbd/3.22/libgnomekbd-3.22.0.1.tar.xz : 4efdb6b8ec92f04caced710b5edb285fb27715059ed6ca5e100b6933999a93de
homepage   : http://www.gnome.org
license    : LGPL-2.0
component  : desktop.gnome.core
summary    : XKB Hooks used by the GNOME Desktop
description: |
    The libgnomekbd package contains xkb hooks used by the GNOME Desktop.
builddeps  :
    - pkgconfig(gdk-3.0)
    - pkgconfig(libxklavier)
    - pkgconfig(ice)
    - intltool
rundeps    :
    - xmodmap
setup      : |
    %configure --disable-static \
               --disable-schemas-compile
build      : |
    %make
install    : |
    %make_install
