name       : libgnomekbd
version    : 3.22.0
release    : 7
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/libgnomekbd/3.22/libgnomekbd-3.22.0.tar.xz : 340b30dabfebbd4e0e6c0fe34a378966dd5640b5d44595ab8a19b0be255d77df
homepage   : http://www.gnome.org
license    : LGPL-2.0
component  : desktop.gnome.core
summary    : XKB Hooks used by the GNOME Desktop
description: |
    The libgnomekbd package contains xkb hooks used by the GNOME Desktop.
builddeps  :
    - pkgconfig(gdk-3.0)
    - pkgconfig(libxklavier)
rundeps    :
    - xmodmap
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
