name        : libgnomekbd
version     : 3.6.0
release     : 6
source      :
    - http://ftp.gnome.org/pub/gnome/sources/libgnomekbd/3.6/libgnomekbd-3.6.0.tar.xz : c41ea5b0f64da470925ba09f9f1b46b26b82d4e433e594b2c71eab3da8856a09
homepage    : http://www.gnome.org
license     :
    - LGPL-2.0
summary     : XKB Hooks used by the GNOME Desktop
builddeps   :
    - pkgconfig(gdk-3.0)
    - pkgconfig(libxklavier)
rundeps     :
    - xmodmap
description : |
    The libgnomekbd package contains xkb hooks used by the GNOME Desktop.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
